table Plan

	column 'customer_id'
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id

	column 'customer_level'
		dataType: string
		summarizeBy: none
		sourceColumn: customer_level

	column 'risk_segment'
		dataType: string
		summarizeBy: none
		sourceColumn: risk_segment

	column 'recency'
		dataType: double
		summarizeBy: none
		sourceColumn: recency

	column 'frequency'
		dataType: double
		summarizeBy: none
		sourceColumn: frequency

	column 'monetary'
		dataType: double
		summarizeBy: none
		sourceColumn: monetary

	column 'rfm_score'
		dataType: double
		summarizeBy: none
		sourceColumn: rfm_score

	column 'churn_probability'
		dataType: double
		summarizeBy: none
		sourceColumn: churn_probability

	column 'lifetime_value'
		dataType: double
		summarizeBy: none
		sourceColumn: lifetime_value

	column 'churn_risk_pct'
		dataType: double
		summarizeBy: none
		sourceColumn: churn_risk_pct

	column 'Estrategia'
		dataType: string
		summarizeBy: none
		sourceColumn: Estrategia

	column 'Urgencia'
		dataType: string
		summarizeBy: none
		sourceColumn: Urgencia

	column 'RetornoHipotetico'
		dataType: double
		summarizeBy: none
		sourceColumn: RetornoHipotetico

	column 'InversionHipotetica'
		dataType: double
		summarizeBy: none
		sourceColumn: InversionHipotetica

	measure KPI_VIP = COUNTROWS(Plan)
		formatString: #,0.00
		displayFolder: Indicadores

	measure KPI_Inversion = SUM(Plan[InversionHipotetica])
		formatString: #,0.00
		displayFolder: Indicadores

	measure KPI_Retorno = SUM(Plan[RetornoHipotetico])
		formatString: #,0.00
		displayFolder: Indicadores

	partition Plan = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Plan.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"customer_id", type text}, {"customer_level", type text}, {"risk_segment", type text}, {"recency", type number}, {"frequency", type number}, {"monetary", type number}, {"rfm_score", type number}, {"churn_probability", type number}, {"lifetime_value", type number}, {"churn_risk_pct", type number}, {"Estrategia", type text}, {"Urgencia", type text}, {"RetornoHipotetico", type number}, {"InversionHipotetica", type number}}, "en-US")
				in
				    Typed
